### ISSUE TITLE
Unable to restore s3 repostory snapshot to another cluster with upgraded version. 

### ISSUE THREAD

**Issue by pammi22** [opendistro-for-elasticsearch/community#141]
We have cluster snapshot of opendistro version 0.9.0.0 and we are trying to restore this snapshot to opendistro version 1.2.0 but we are getting the below mentioned error. 
can anyone help? i have verified the blob file exists in the s3 repository. 
Restore request body: 
{
  "indices": "myindexpattern-*",
  "include_global_state": false,
   "include_aliases": false,
 "partial": false
}

`[2019-12-04T19:45:50,928][WARN ][r.suppressed             ] [node3] path: /_snapshot/xxxxx/04-12-2019/_restore, params: {repository=xxxxx, snapshot=04-12-2019}
org.elasticsearch.transport.RemoteTransportException: [node1][xxxxxxxxx:9300][cluster:admin/snapshot/restore]
Caused by: java.nio.file.NoSuchFileException: Blob object [meta-8HHg4xTvT16UCKaYebHo4A.dat] not found: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 48C0342581D36A25; S3 Extended Request ID: +hV9hb0l/sGfmxBAOy2F0sIwcLB9n98Iwg4WAuiV/sqDN/vkjQAu4/Mviy4uB1JJO6S+ztNUf4k=)
	at org.elasticsearch.repositories.s3.S3BlobContainer.readBlob(S3BlobContainer.java:93) ~[?:?]
	at org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.readBlob(ChecksumBlobStoreFormat.java:101) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.repositories.blobstore.BlobStoreFormat.read(BlobStoreFormat.java:90) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getSnapshotIndexMetaData(BlobStoreRepository.java:573) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.snapshots.RestoreService.restoreSnapshot(RestoreService.java:212) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.action.admin.cluster.snapshots.restore.TransportRestoreSnapshotAction.masterOperation(TransportRestoreSnapshotAction.java:77) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.action.admin.cluster.snapshots.restore.TransportRestoreSnapshotAction.masterOperation(TransportRestoreSnapshotAction.java:38) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:127) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$1.doRun(TransportMasterNodeAction.java:200) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:758) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.2.0.jar:7.2.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]`

**Comment by alolita** [comment]
Hi @pammi22 following up - were you able to solve this snapshot issue?

**Comment by tinh1115** [comment]
I'm having same issue:

shard has failed to be restored from the snapshot [elasticsearchToS3:snapshotelasticsearch-12-09-2020/9DmXS7PRT_edvh8PjXS1pA] because of [failed shard on node [PRPpFmkDSr63_AXoPXN3XA]: failed recovery, failure RecoveryFailedException[[our_index_name][1]: Recovery failed on {PRPpFmk}{PRPpFmkDSr63_AXoPXN3XA}{6RE7iSDfS2iCkQ98DkaJqw}{10.0.111.94}{10.0.111.94:9300}]; nested: IndexShardRecoveryException[failed recovery]; nested: IndexShardRestoreFailedException[restore failed]; nested: IndexShardRestoreFailedException[failed to restore snapshot [snapshotelasticsearch-12-09-2020/9DmXS7PRT_edvh8PjXS1pA]]; nested: IndexShardRestoreFailedException[Failed to recover index]; nested: NoSuchFileException[Blob object [__2kr] not found: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 33ADD12143267B50; S3 Extended Request ID: /ZkFmcZRacw8Euo8LCjBy1vK5BYcZtfDGxC3gvH9+723o2q4HoBcAN+uVyUj59hPx4XV/BCrXmY=)]; ] - manually close or delete the index [our_index_name] in order to retry to restore the snapshot again or use the reroute API to force the allocation of an empty primary shard

Could it be actual file missing from the creation snapshot or issue in s3?
Will give another update if I can fix it.

**Comment by jcgraybill** [comment]
Closing for now. @pammi22 and @tinh1115 if you're still looking for help, feel free to post a question to the [Open Distro forum](https://discuss.opendistrocommunity.dev/).
