### ISSUE TITLE
Error installing opendistro-index-management plugin due to missing dependency

### ISSUE THREAD

**Issue by eoinreilly93** [opendistro-for-elasticsearch/community#168]
I've followed the instruction for installing the opendistro standalone plugins [here](https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/#index-state-management) but I get the following error
```

[root@c09c2b709732 elasticsearch]# bin/elasticsearch-plugin install https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-index-management/opendistro_index_management-1.6.0.0.zip
-> Installing https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-index-management/opendistro_index_management-1.6.0.0.zip
-> Downloading https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-index-management/opendistro_index_management-1.6.0.0.zip
[=================================================] 100%??
-> Failed installing https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-index-management/opendistro_index_management-1.6.0.0.zip
-> Rolling back https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-index-management/opendistro_index_management-1.6.0.0.zip
-> Rolled back https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-index-management/opendistro_index_management-1.6.0.0.zip
Exception in thread "main" java.lang.IllegalArgumentException: Missing plugin [opendistro-job-scheduler], dependency of [opendistro_index_management]
        at org.elasticsearch.plugins.PluginsService.addSortedBundle(PluginsService.java:452)
        at org.elasticsearch.plugins.PluginsService.sortBundles(PluginsService.java:424)
        at org.elasticsearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:847)
        at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:821)
        at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:866)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:254)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:224)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:91)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
```

Is this normal? I don't see any instructions on that page for how to install the missing `opendistro-job-scheduler` plugin. I have seen that I can go to the github page and build it from source and install it that way, but that does not seem a very efficient way if I have to do it every time I want to upgrade to a newer version. 

Is there a link directly to the zip file similar to the other ones (i.e. https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-index-management/opendistro_index_management-1.6.0.0.zip) that I can download instead?

**Comment by dbbaughe** [comment]
Hi @eoinreilly93,

Yes, the Index Management plugin needs the Job Scheduler plugin to be installed first.
The Job Scheduler plugin could be downloaded from here:

https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-job-scheduler/opendistro-job-scheduler-1.6.0.0.zip

Seems like the _ vs - probably throws people off and this page should have direct links to downloads rather than making people put it together.
https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/
