### ISSUE TITLE
Opendistro 1.9 error: SSL contains non-LDH ASCII characters.

### ISSUE THREAD

**Issue by jjmerchante** [opendistro-for-elasticsearch/community#194]
I am testing OpenDistro 1.9, but I am unable to use Kibana correctly. Sometimes I get some errors (`[esaggs] > Internal Server Error` or `[timelion_vis] > Timelion request error: undefined Error: in cell #1: No Living connections` or an empty discovery), but sometimes it works... 

Elasticsearch error:
```
[2020-07-10T08:32:41,397][ERROR][c.a.o.s.s.h.n.OpenDistroSecuritySSLNettyHttpServerTransport] [elastic_service] Exception during establishing a SSL connection: java.lang.IllegalArgumentException: Contains non-LDH ASCII characters
java.lang.IllegalArgumentException: Contains non-LDH ASCII characters
	at java.net.IDN.toASCIIInternal(IDN.java:296) ~[?:?]
	at java.net.IDN.toASCII(IDN.java:122) ~[?:?]
	at javax.net.ssl.SNIHostName.<init>(SNIHostName.java:99) ~[?:?]
	at sun.security.ssl.SSLSessionImpl.<init>(SSLSessionImpl.java:423) ~[?:?]
	at sun.security.ssl.SessionTicketExtension$T12CHSessionTicketConsumer.consume(SessionTicketExtension.java:470) ~[?:?]
	at sun.security.ssl.SSLExtension.consumeOnLoad(SSLExtension.java:581) ~[?:?]
	at sun.security.ssl.SSLExtensions.consumeOnLoad(SSLExtensions.java:186) ~[?:?]
	at sun.security.ssl.ClientHello$T12ClientHelloConsumer.consume(ClientHello.java:975) ~[?:?]
	at sun.security.ssl.ClientHello$ClientHelloConsumer.onClientHello(ClientHello.java:853) ~[?:?]
	at sun.security.ssl.ClientHello$ClientHelloConsumer.consume(ClientHello.java:812) ~[?:?]
	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396) ~[?:?]
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:445) ~[?:?]
	at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1260) ~[?:?]
	at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1247) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:691) ~[?:?]
	at sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1192) ~[?:?]
	at io.netty.handler.ssl.SslHandler.runAllDelegatedTasks(SslHandler.java:1542) ~[netty-handler-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1556) ~[netty-handler-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1440) ~[netty-handler-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1267) ~[netty-handler-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1314) ~[netty-handler-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) ~[netty-codec-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) ~[netty-codec-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[2020-07-10T08:32:41,398][WARN ][o.e.h.AbstractHttpServerTransport] [elastic_service] caught exception while handling client http traffic, closing connection Netty4HttpChannel{localAddress=/172.18.0.4:9200, remoteAddress=/172.18.0.10:41850}
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Contains non-LDH ASCII characters
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:471) ~[netty-codec-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.IllegalArgumentException: Contains non-LDH ASCII characters
	at java.net.IDN.toASCIIInternal(IDN.java:296) ~[?:?]
	at java.net.IDN.toASCII(IDN.java:122) ~[?:?]
	at javax.net.ssl.SNIHostName.<init>(SNIHostName.java:99) ~[?:?]
	at sun.security.ssl.SSLSessionImpl.<init>(SSLSessionImpl.java:423) ~[?:?]
	at sun.security.ssl.SessionTicketExtension$T12CHSessionTicketConsumer.consume(SessionTicketExtension.java:470) ~[?:?]
	at sun.security.ssl.SSLExtension.consumeOnLoad(SSLExtension.java:581) ~[?:?]
	at sun.security.ssl.SSLExtensions.consumeOnLoad(SSLExtensions.java:186) ~[?:?]
	at sun.security.ssl.ClientHello$T12ClientHelloConsumer.consume(ClientHello.java:975) ~[?:?]
	at sun.security.ssl.ClientHello$ClientHelloConsumer.onClientHello(ClientHello.java:853) ~[?:?]
	at sun.security.ssl.ClientHello$ClientHelloConsumer.consume(ClientHello.java:812) ~[?:?]
	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396) ~[?:?]
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:445) ~[?:?]
	at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1260) ~[?:?]
	at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1247) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:691) ~[?:?]
	at sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1192) ~[?:?]
	at io.netty.handler.ssl.SslHandler.runAllDelegatedTasks(SslHandler.java:1542) ~[netty-handler-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1556) ~[netty-handler-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1440) ~[netty-handler-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1267) ~[netty-handler-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1314) ~[netty-handler-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) ~[netty-codec-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) ~[netty-codec-4.1.49.Final.jar:4.1.49.Final]
	... 16 more
```
Kibana error:
```
{"type":"response","@timestamp":"2020-07-10T08:32:39Z","tags":[],"pid":1,"method":"get","statusCode":200,"req":{"url":"/translations/en.json","method":"get","headers":{"host":"kibana","connection":"close","user-agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0","accept":"*/*","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","referer":"https://localhost:9000/kibana/app/kibana","dnt":"1"},"remoteAddress":"172.18.0.13","userAgent":"172.18.0.13","referer":"https://localhost:9000/kibana/app/kibana"},"res":{"statusCode":200,"responseTime":5,"contentLength":9},"message":"GET /translations/en.json 200 5ms - 9.0B"}
{"type":"response","@timestamp":"2020-07-10T08:32:40Z","tags":[],"pid":1,"method":"post","statusCode":200,"req":{"url":"/api/core/capabilities","method":"post","headers":{"host":"kibana","connection":"close","content-length":"347","user-agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0","accept":"*/*","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","referer":"https://localhost:9000/kibana/app/kibana","content-type":"application/json","kbn-version":"7.8.0","origin":"https://localhost:9000","dnt":"1","securitytenant":""},"remoteAddress":"172.18.0.13","userAgent":"172.18.0.13","referer":"https://localhost:9000/kibana/app/kibana"},"res":{"statusCode":200,"responseTime":12,"contentLength":9},"message":"POST /api/core/capabilities 200 12ms - 9.0B"}
{"type":"log","@timestamp":"2020-07-10T08:32:41Z","tags":["error","elasticsearch","security"],"pid":1,"message":"Request error, retrying\nGET https://elastic_service:9200/_opendistro/_security/authinfo => Client network socket disconnected before secure TLS connection was established"}
{"type":"log","@timestamp":"2020-07-10T08:32:41Z","tags":["warning","elasticsearch","security"],"pid":1,"message":"Unable to revive connection: https://elastic_service:9200/"}
{"type":"log","@timestamp":"2020-07-10T08:32:41Z","tags":["warning","elasticsearch","security"],"pid":1,"message":"No living connections"}
{"type":"error","@timestamp":"2020-07-10T08:32:41Z","tags":[],"pid":1,"level":"error","error":{"message":"No Living connections: No Living connections","name":"Error","stack":"Error: No Living connections: No Living connections\n    at sendReqWithConnection (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:266:15)\n    at next (/usr/share/kibana/node_modules/elasticsearch/src/lib/connection_pool.js:243:7)\n    at process._tickCallback (internal/process/next_tick.js:61:11)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":null,"query":{},"pathname":"/api/v1/auth/authinfo","path":"/api/v1/auth/authinfo","href":"/api/v1/auth/authinfo"},"message":"No Living connections: No Living connections"}
{"type":"response","@timestamp":"2020-07-10T08:32:41Z","tags":[],"pid":1,"method":"get","statusCode":500,"req":{"url":"/api/v1/auth/authinfo","method":"get","headers":{"host":"kibana","connection":"close","user-agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0","accept":"application/json, text/plain, */*","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","kbn-version":"7.8.0","dnt":"1","referer":"https://localhost:9000/kibana/app/kibana","securitytenant":""},"remoteAddress":"172.18.0.13","userAgent":"172.18.0.13","referer":"https://localhost:9000/kibana/app/kibana"},"res":{"statusCode":500,"responseTime":31,"contentLength":9},"message":"GET /api/v1/auth/authinfo 500 31ms - 9.0B"}
```

Kibana configuration:
```
server.name: kibana
server.host: "0"
server.basePath: "/kibana"
server.rewriteBasePath: true

elasticsearch.hosts: https://elastic_service:9200
elasticsearch.ssl.verificationMode: none
elasticsearch.username: kibanaserver
elasticsearch.password: test-password
elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]

server.ssl.enabled: false

opendistro_security.multitenancy.enabled: true
opendistro_security.multitenancy.tenants.enable_private: false
opendistro_security.multitenancy.tenants.preferred: ["Global"]
opendistro_security.readonly_mode.roles: ["kibana_read_only"]

opendistro_security.auth.type: "jwt"
opendistro_security.jwt.url_param: jwtToken

newsfeed.enabled: false
telemetry.optIn: false
telemetry.enabled: false
```

- I am using containers `amazon/opendistro-for-elasticsearch:1.9.0` and `amazon/opendistro-for-elasticsearch-kibana:1.9.0`.
- I am authenticated as admin using JWT.
- In the errors, `172.18.0.4` is elasticsearch and `172.18.0.10` is Kibana.
- Doing exactly the same in Opendistro 1.8.0 works
- We perform queries to Elasticsearch without using kibana and we don't get any errors

You can ask me for more information if needed,

Thank you

**Comment by jjmerchante** [comment]
I've been researching the problem, and I've found that the only place where I use LDH characters is in container names. For example, for the Elasticsearch name, I am using `elastic_service` (it is the name for `elasticsearch.hosts` in Kibana). I have changed the name to `elastic` and created again the root, admin and node certificates and it does not fail.
Still I don't understand why it starts to fail:
- I can't find any change in ElasticSearch that causes this error.
- It doesn't always fail, sometimes it shows a dashboard without errors and others it gives you an error in some visualizations.

**Comment by sastorsl** [comment]
I'm facing similar issues, and the fun thing is the different components in ELK reacts differently.
Logstash seems to fail entirely when connecting to by my docker container names, so I changed to using the host names since I'm allready exposing elasticsearch.

But it seems to affect the kibana --> elasticsearch connection as well, but not in the same way.
I'm able to connect, but it fails at intervals - my guess is different components in kibana.

Usually a user refresh fixes the issue.

The issue is that underscores in FQDNs are not allowed, and a strict TLS check will and should reject it.
[Underscores not allowed in FQDNs](https://www.digicert.com/kb/ssl-support/underscores-not-allowed-in-fqdns.htm)

Example error:

`io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Contains non-LDH ASCII characters`

I'll either rename my containers or go back to using the server hostname instead.
