### ISSUE TITLE
"Physical memory size could not be determined" error when starting opendistro in openvz container

### ISSUE THREAD

**Issue by amasolini** [opendistro-for-elasticsearch/community#197]
Hi there.

After going through the easy to follow steps for installing opendistro (from this link: https://opendistro.github.io/for-elasticsearch-docs/docs/install/rpm/), starting the service gives me the following error.

**Error:** 
**"Physical memory size could not be determined"**

**Platform:** CentOS 8 under OpenVZ 7 / Virtuozzo7
**Version of OpenDistro**: 1.9.0

**StackTrace:**
`[2020-07-13T09:38:18,712][INFO ][o.e.n.Node               ] [od.domain.com] version[7.8.0], pid[27316], build[oss/rpm/757314695644ea9a1dc2fecd26d1a43856725e65/2020-06-14T19:35:50.234439Z], OS[Linux/4.18.0/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/14.0.1/14.0.1+7]
[2020-07-13T09:38:18,715][INFO ][o.e.n.Node               ] [od.domain.com] JVM home [/usr/share/elasticsearch/jdk]
[2020-07-13T09:38:18,715][INFO ][o.e.n.Node               ] [od.domain.com] JVM arguments [-Xshare:auto, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=SPI,COMPAT, -Xms1g, -Xmx1g, -XX:+UseG1GC, -XX:G1ReservePercent=25, -XX:InitiatingHeapOccupancyPercent=30, -Djava.io.tmpdir=/tmp/elasticsearch-7745996861696586237, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=/var/lib/elasticsearch, -XX:ErrorFile=/var/log/elasticsearch/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/elasticsearch/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Dclk.tck=100, -Djdk.attach.allowAttachSelf=true, -Djava.security.policy=file:///usr/share/elasticsearch/plugins/opendistro_performance_analyzer/pa_config/es_security.policy, -XX:MaxDirectMemorySize=536870912, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/etc/elasticsearch, -Des.distribution.flavor=oss, -Des.distribution.type=rpm, -Des.bundled_jdk=true]
[2020-07-13T09:38:19,335][INFO ][c.a.o.e.p.c.PluginSettings] [od.domain.com] Config: metricsLocation: /dev/shm/performanceanalyzer/, metricsDeletionInterval: 1, httpsEnabled: false, cleanup-metrics-db-files: true
[2020-07-13T09:38:19,503][INFO ][c.a.o.s.OpenDistroSecurityPlugin] [od.domain.com] ES Config path is /etc/elasticsearch
[2020-07-13T09:38:19,636][INFO ][c.a.o.s.s.DefaultOpenDistroSecurityKeyStore] [od.domain.com] JVM supports TLSv1.3
[2020-07-13T09:38:19,637][INFO ][c.a.o.s.s.DefaultOpenDistroSecurityKeyStore] [od.domain.com] Config directory is /etc/elasticsearch/, from there the key- and truststore files are resolved relatively
[2020-07-13T09:38:20,080][INFO ][c.a.o.s.s.DefaultOpenDistroSecurityKeyStore] [od.domain.com] TLS Transport Client Provider : JDK
[2020-07-13T09:38:20,081][INFO ][c.a.o.s.s.DefaultOpenDistroSecurityKeyStore] [od.domain.com] TLS Transport Server Provider : JDK
[2020-07-13T09:38:20,081][INFO ][c.a.o.s.s.DefaultOpenDistroSecurityKeyStore] [od.domain.com] TLS HTTP Provider             : JDK
[2020-07-13T09:38:20,081][INFO ][c.a.o.s.s.DefaultOpenDistroSecurityKeyStore] [od.domain.com] Enabled TLS protocols for transport layer : [TLSv1.3, TLSv1.2, TLSv1.1]
[2020-07-13T09:38:20,081][INFO ][c.a.o.s.s.DefaultOpenDistroSecurityKeyStore] [od.domain.com] Enabled TLS protocols for HTTP layer      : [TLSv1.3, TLSv1.2, TLSv1.1]
[2020-07-13T09:38:20,233][INFO ][c.a.o.s.OpenDistroSecurityPlugin] [od.domain.com] Clustername: elasticsearch
[2020-07-13T09:38:20,237][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [od.domain.com] File /etc/elasticsearch/esnode-key.pem has insecure file permissions (should be 0600)
[2020-07-13T09:38:20,237][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [od.domain.com] File /etc/elasticsearch/.elasticsearch.keystore.initial_md5sum has insecure file permissions (should be 0600)
[2020-07-13T09:38:20,238][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [od.domain.com] File /etc/elasticsearch/root-ca.pem has insecure file permissions (should be 0600)
[2020-07-13T09:38:20,238][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [od.domain.com] File /etc/elasticsearch/kirk-key.pem has insecure file permissions (should be 0600)
[2020-07-13T09:38:20,238][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [od.domain.com] File /etc/elasticsearch/esnode.pem has insecure file permissions (should be 0600)
[2020-07-13T09:38:20,238][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [od.domain.com] File /etc/elasticsearch/kirk.pem has insecure file permissions (should be 0600)
[2020-07-13T09:38:20,317][INFO ][c.a.o.j.JobSchedulerPlugin] [od.domain.com] Loaded scheduler extension: opendistro_anomaly_detector, index: .opendistro-anomaly-detector-jobs
[2020-07-13T09:38:20,408][INFO ][c.a.o.j.JobSchedulerPlugin] [od.domain.com] Loaded scheduler extension: opendistro-managed-index, index: .opendistro-ism-config
[2020-07-13T09:38:20,449][INFO ][o.e.p.PluginsService     ] [od.domain.com] loaded module [aggs-matrix-stats]
[2020-07-13T09:38:20,449][INFO ][o.e.p.PluginsService     ] [od.domain.com] loaded module [analysis-common]
[2020-07-13T09:38:20,450][INFO ][o.e.p.PluginsService     ] [od.domain.com] loaded module [geo]
[2020-07-13T09:38:20,450][INFO ][o.e.p.PluginsService     ] [od.domain.com] loaded module [ingest-common]
[2020-07-13T09:38:20,450][INFO ][o.e.p.PluginsService     ] [od.domain.com] loaded module [ingest-geoip]
[2020-07-13T09:38:20,450][INFO ][o.e.p.PluginsService     ] [od.domain.com] loaded module [ingest-user-agent]
[2020-07-13T09:38:20,450][INFO ][o.e.p.PluginsService     ] [od.domain.com] loaded module [kibana]
[2020-07-13T09:38:20,450][INFO ][o.e.p.PluginsService     ] [od.domain.com] loaded module [lang-expression]
[2020-07-13T09:38:20,450][INFO ][o.e.p.PluginsService     ] [od.domain.com] loaded module [lang-mustache]
[2020-07-13T09:38:20,451][INFO ][o.e.p.PluginsService     ] [od.domain.com] loaded module [lang-painless]
[2020-07-13T09:38:20,451][INFO ][o.e.p.PluginsService     ] [od.domain.com] loaded module [mapper-extras]
[2020-07-13T09:38:20,451][INFO ][o.e.p.PluginsService     ] [od.domain.com] loaded module [parent-join]
[2020-07-13T09:38:20,451][INFO ][o.e.p.PluginsService     ] [od.domain.com] loaded module [percolator]
[2020-07-13T09:38:20,451][INFO ][o.e.p.PluginsService     ] [od.domain.com] loaded module [rank-eval]
[2020-07-13T09:38:20,451][INFO ][o.e.p.PluginsService     ] [od.domain.com] loaded module [reindex]
[2020-07-13T09:38:20,451][INFO ][o.e.p.PluginsService     ] [od.domain.com] loaded module [repository-url]
[2020-07-13T09:38:20,452][INFO ][o.e.p.PluginsService     ] [od.domain.com] loaded module [systemd]
[2020-07-13T09:38:20,452][INFO ][o.e.p.PluginsService     ] [od.domain.com] loaded module [tasks]
[2020-07-13T09:38:20,452][INFO ][o.e.p.PluginsService     ] [od.domain.com] loaded module [transport-netty4]
[2020-07-13T09:38:20,452][INFO ][o.e.p.PluginsService     ] [od.domain.com] loaded plugin [opendistro-anomaly-detection]
[2020-07-13T09:38:20,452][INFO ][o.e.p.PluginsService     ] [od.domain.com] loaded plugin [opendistro-job-scheduler]
[2020-07-13T09:38:20,453][INFO ][o.e.p.PluginsService     ] [od.domain.com] loaded plugin [opendistro-knn]
[2020-07-13T09:38:20,453][INFO ][o.e.p.PluginsService     ] [od.domain.com] loaded plugin [opendistro_alerting]
[2020-07-13T09:38:20,453][INFO ][o.e.p.PluginsService     ] [od.domain.com] loaded plugin [opendistro_index_management]
[2020-07-13T09:38:20,453][INFO ][o.e.p.PluginsService     ] [od.domain.com] loaded plugin [opendistro_performance_analyzer]
[2020-07-13T09:38:20,453][INFO ][o.e.p.PluginsService     ] [od.domain.com] loaded plugin [opendistro_security]
[2020-07-13T09:38:20,453][INFO ][o.e.p.PluginsService     ] [od.domain.com] loaded plugin [opendistro_sql]
[2020-07-13T09:38:20,467][INFO ][c.a.o.s.OpenDistroSecurityPlugin] [od.domain.com] Disabled https compression by default to mitigate BREACH attacks. You can enable it by setting 'http.compression: true' in elasticsearch.yml
[2020-07-13T09:38:20,484][INFO ][o.e.e.NodeEnvironment    ] [od.domain.com] using [1] data paths, mounts [[/ (rootfs)]], net usable_space [35.7gb], net total_space [39.2gb], types [rootfs]
[2020-07-13T09:38:20,484][INFO ][o.e.e.NodeEnvironment    ] [od.domain.com] heap size [1gb], compressed ordinary object pointers [true]
[2020-07-13T09:38:20,522][INFO ][o.e.n.Node               ] [od.domain.com] node name [od.domain.com], node ID [IBjlzEJJQumk-G8KaD1P8Q], cluster name [elasticsearch]
[2020-07-13T09:38:22,691][ERROR][o.e.b.Bootstrap          ] [od.domain.com] Exception
java.lang.IllegalStateException: Physical memory size could not be determined
	at com.amazon.opendistroforelasticsearch.knn.index.KNNSettings.parseknnMemoryCircuitBreakerValue(KNNSettings.java:323) ~[?:?]
	at com.amazon.opendistroforelasticsearch.knn.index.KNNSettings.lambda$knnMemoryCircuitBreakerSetting$4(KNNSettings.java:309) ~[?:?]
	at org.elasticsearch.common.settings.Setting.getDefault(Setting.java:399) ~[elasticsearch-7.8.0.jar:7.8.0]
	at com.amazon.opendistroforelasticsearch.knn.index.KNNSettings.getSettingValue(KNNSettings.java:241) ~[?:?]
	at com.amazon.opendistroforelasticsearch.knn.index.KNNSettings.getCircuitBreakerLimit(KNNSettings.java:286) ~[?:?]
	at com.amazon.opendistroforelasticsearch.knn.index.KNNIndexCache.initCache(KNNIndexCache.java:94) ~[?:?]
	at com.amazon.opendistroforelasticsearch.knn.index.KNNIndexCache.<init>(KNNIndexCache.java:66) ~[?:?]
	at com.amazon.opendistroforelasticsearch.knn.index.KNNIndexCache.getInstance(KNNIndexCache.java:83) ~[?:?]
	at com.amazon.opendistroforelasticsearch.knn.index.KNNIndexCache.setResourceWatcherService(KNNIndexCache.java:70) ~[?:?]
	at com.amazon.opendistroforelasticsearch.knn.plugin.KNNPlugin.createComponents(KNNPlugin.java:125) ~[?:?]
	at org.elasticsearch.node.Node.lambda$new$11(Node.java:484) ~[elasticsearch-7.8.0.jar:7.8.0]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1624) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at org.elasticsearch.node.Node.<init>(Node.java:488) ~[elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:227) ~[elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:227) ~[elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393) [elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) [elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161) [elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127) [elasticsearch-cli-7.8.0.jar:7.8.0]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-7.8.0.jar:7.8.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126) [elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) [elasticsearch-7.8.0.jar:7.8.0]
[2020-07-13T09:38:23,014][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [od.domain.com] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Physical memory size could not be determined
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:174) ~[elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161) ~[elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127) ~[elasticsearch-cli-7.8.0.jar:7.8.0]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.8.0.jar:7.8.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126) ~[elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.8.0.jar:7.8.0]
Caused by: java.lang.IllegalStateException: Physical memory size could not be determined
	at com.amazon.opendistroforelasticsearch.knn.index.KNNSettings.parseknnMemoryCircuitBreakerValue(KNNSettings.java:323) ~[?:?]
	at com.amazon.opendistroforelasticsearch.knn.index.KNNSettings.lambda$knnMemoryCircuitBreakerSetting$4(KNNSettings.java:309) ~[?:?]
	at org.elasticsearch.common.settings.Setting.getDefault(Setting.java:399) ~[elasticsearch-7.8.0.jar:7.8.0]
	at com.amazon.opendistroforelasticsearch.knn.index.KNNSettings.getSettingValue(KNNSettings.java:241) ~[?:?]
	at com.amazon.opendistroforelasticsearch.knn.index.KNNSettings.getCircuitBreakerLimit(KNNSettings.java:286) ~[?:?]
	at com.amazon.opendistroforelasticsearch.knn.index.KNNIndexCache.initCache(KNNIndexCache.java:94) ~[?:?]
	at com.amazon.opendistroforelasticsearch.knn.index.KNNIndexCache.<init>(KNNIndexCache.java:66) ~[?:?]
	at com.amazon.opendistroforelasticsearch.knn.index.KNNIndexCache.getInstance(KNNIndexCache.java:83) ~[?:?]
	at com.amazon.opendistroforelasticsearch.knn.index.KNNIndexCache.setResourceWatcherService(KNNIndexCache.java:70) ~[?:?]
	at com.amazon.opendistroforelasticsearch.knn.plugin.KNNPlugin.createComponents(KNNPlugin.java:125) ~[?:?]
	at org.elasticsearch.node.Node.lambda$new$11(Node.java:484) ~[elasticsearch-7.8.0.jar:7.8.0]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1624) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at org.elasticsearch.node.Node.<init>(Node.java:488) ~[elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:227) ~[elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:227) ~[elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393) ~[elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.8.0.jar:7.8.0]
	... 6 more
[2020-07-13T09:39:19,380][INFO ][stats_log                ] [od.domain.com] ------------------------------------------------------------------------
Program=PerformanceAnalyzerPlugin
rca-version=0.0.1
StartTime=1594651099.356
EndTime=Mon, 13 Jul 2020 09:39:19 GMT-05:00
Time=60010 msecs
Timing=total-time:60010.0/1
Counters=TotalError=0,MasterNodeNotUp=56
EOE
[2020-07-13T09:39:19,424][INFO ][stats_log                ] [od.domain.com] ------------------------------------------------------------------------
Program=PerformanceAnalyzerPlugin
rca-version=0.0.1
Metrics=
StartTime=0.000
EndTime=Mon, 13 Jul 2020 09:39:19 GMT-05:00
Time=1594651159414 msecs
Timing=total-time:1.594651159414E12/1
Counters=
EOE
[2020-07-13T09:39:19,425][INFO ][stats_log                ] [od.domain.com] ------------------------------------------------------------------------
Program=PerformanceAnalyzerPlugin
rca-version=0.0.1
Metrics=
StartTime=0.000
EndTime=Mon, 13 Jul 2020 09:39:19 GMT-05:00
Time=1594651159424 msecs
Timing=total-time:1.594651159424E12/1
Counters=
EOE
[2020-07-13T09:39:19,426][INFO ][stats_log                ] [od.domain.com] ------------------------------------------------------------------------
Program=PerformanceAnalyzerPlugin
rca-version=0.0.1
Metrics=
StartTime=0.000
EndTime=Mon, 13 Jul 2020 09:39:19 GMT-05:00
Time=1594651159425 msecs
Timing=total-time:1.594651159425E12/1
Counters=
EOE
[2020-07-13T09:39:19,427][INFO ][stats_log                ] [od.domain.com] ------------------------------------------------------------------------
Program=PerformanceAnalyzerPlugin
rca-version=0.0.1
Metrics=
StartTime=0.000
EndTime=Mon, 13 Jul 2020 09:39:19 GMT-05:00
Time=1594651159426 msecs
Timing=total-time:1.594651159426E12/1
Counters=
EOE
[2020-07-13T09:39:19,428][INFO ][stats_log                ] [od.domain.com] ------------------------------------------------------------------------
Program=PerformanceAnalyzerPlugin
rca-version=0.0.1
Metrics=JvmFreeMem=818462560 bytes aggr|SAMPLE,RcaEnabled=0 count aggr|SAMPLE,JvmTotalMem=1073741824 bytes aggr|SAMPLE
StartTime=1594651159.414
EndTime=Mon, 13 Jul 2020 09:39:19 GMT-05:00
Time=13 msecs
Timing=total-time:13.0/1
Counters=
EOE`

**Notes:** I'm experiencing exactly the same issue with CentOS 7, as well as with version 1.8 of OpenDistro. Installing Elasticsearch from the original project works like a charm.

**Comment by YJesus** [comment]
Confirmed also in Debian 9 and 10. 

Elastic.co --> OK

OpenDistro --> FAIL

**Comment by jcgraybill** [comment]
Hi, if you're still looking for help with this, go ahead and post a question to the [Open Distro forums](https://discuss.opendistrocommunity.dev/). Thanks!

**Comment by vladaman** [comment]
I am having same issue. Open Distro Forums has no responses on this topic either.
