### ISSUE TITLE
opendistro not compatible with kafka-connect-elasticsearch

### ISSUE THREAD

**Issue by agujrathi** [opendistro-for-elasticsearch/community#200]
Hi team,

I was trying out kafka-connect-elasticsearch.
https://docs.confluent.io/current/connect/kafka-connect-elasticsearch/security.html

From the configuration, looks like it has config mentioned considering xpack as referance.
Below is my configuration in elasticsearch.yml

```
opendistro_security.ssl.transport.keystore_type: JKS
opendistro_security.ssl.transport.keystore_filepath: /opt/bika/elasticsearch/config/certs/keystore.jks
opendistro_security.ssl.transport.keystore_password: bika123
opendistro_security.ssl.transport.truststore_type: JKS
opendistro_security.ssl.transport.truststore_filepath: /opt/bika/elasticsearch/config/certs/truststore.jks
opendistro_security.ssl.transport.truststore_password: bika123

opendistro_security.ssl.http.keystore_type: JKS
opendistro_security.ssl.http.keystore_filepath: /opt/bika/elasticsearch/config/certs/keystore.jks
opendistro_security.ssl.http.keystore_password: bika123
opendistro_security.ssl.http.truststore_type: JKS
opendistro_security.ssl.http.truststore_filepath: /opt/bika/elasticsearch/config/certs/truststore.jks
opendistro_security.ssl.http.truststore_password: bika123


opendistro_security.ssl.transport.enforce_hostname_verification: false
opendistro_security.ssl.http.enabled: true

opendistro_security.allow_unsafe_democertificates: true
opendistro_security.allow_default_init_securityindex: true
opendistro_security.authcz.admin_dn:
   - "EMAILADDRESS=abhi@gmail.com,CN=abhi,OU=dev,O=Pr,L=Pune,ST=MH,C=IN"
        #  - CN=kirk,OU=client,O=client,L=test,C=de
opendistro_security.audit.type: internal_elasticsearch
opendistro_security.enable_snapshot_restore_privilege: true
opendistro_security.check_snapshot_restore_write_privileges: true
opendistro_security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
cluster.routing.allocation.disk.threshold_enabled: false
network.host: localhost
node.name: smoketestnode
cluster.initial_master_nodes: smoketestnode
node.max_local_storage_nodes: 3
######## End OpenDistro for Elasticsearch Security Demo Configuration ########
```

I used selfsigned cetificates and started elasticseach.. It started properly.

Below is the config in **kafka-connect-elasticsearch**

```
name=elasticsearch-sink
#connector.class=org.apache.kafka.connect.file.FileStreamSinkConnector
#connector.class=ElasticsearchSinkConnector
connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
#connection.url=https://localhost:9200
connection.url=https://localhost:9200
tasks.max=1
topics=bika
type.name=kafka-connect
connection.username="admin"
connection.password="admin"
elasticsearch.username="admin"
elasticsearch.password="admin"
ssl.client.auth=false
elasticsearch.ssl.verificationMode: false
ssl_certificate_verification: false
key.ignore=true
schema.ignore = true
topic.key.ignore = 'bika'

elastic.security.protocol = SSL

opendistro_security.ssl.transport.keystore_type: JKS
opendistro_security.ssl.transport.keystore_filepath: /opt/bika/elasticsearch/config/certs/keystore.jks
opendistro_security.ssl.transport.keystore_password: bika123
opendistro_security.ssl.transport.truststore_type: JKS
opendistro_security.ssl.transport.truststore_filepath: /opt/bika/elasticsearch/config/certs/truststore.jks
opendistro_security.ssl.transport.truststore_password: bika123

```

Always, getting error as below in kafka-elastic-connector side...as below:

```
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find v
alid certification path to requested target
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
        at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1323)
        ... 49 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)

```

Below logs in elasticsearch side..

```
[2020-08-03T21:59:55,327][WARN ][o.e.h.AbstractHttpServerTransport] [smoketestnode] caught exception while handling client http traffic, closing connection Netty4HttpChannel{localAddress=/127.0.0.1:9200, remoteAddress=/127.0.0.1:38660}
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
```

If, any configuration issue, please let me know , will check that..
Or great if anyone has this working.. please let me know the correct steps..
Hope this is not an issue ?? but not a single post around this...

**Comment by jcgraybill** [comment]
Hi, if you're still looking for help with this, go ahead and post a question to the [Open Distro forums](https://discuss.opendistrocommunity.dev/). Thanks!
