### ISSUE TITLE
Physical memory size could not be determined on opendistro 1.3.1

### ISSUE THREAD

**Issue by vladaman** [opendistro-for-elasticsearch/community#266]
Unfortunately I have same issue and I ma reopening ticket #197 - unfortunately Open Distro Forums have no solution to this. 

```
[2022-04-16T15:43:43,109][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [vp003.vps] uncaught exception in thread [main]
org.opensearch.bootstrap.StartupException: java.lang.IllegalStateException: Physical memory size could not be determined
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182) ~[opensearch-1.3.1.jar:1.3.1]
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:169) ~[opensearch-1.3.1.jar:1.3.1]
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100) ~[opensearch-1.3.1.jar:1.3.1]
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-1.3.1.jar:1.3.1]
	at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-1.3.1.jar:1.3.1]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:135) ~[opensearch-1.3.1.jar:1.3.1]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101) ~[opensearch-1.3.1.jar:1.3.1]
Caused by: java.lang.IllegalStateException: Physical memory size could not be determined
	at org.opensearch.knn.index.KNNSettings.parseknnMemoryCircuitBreakerValue(KNNSettings.java:374) ~[?:?]
	at org.opensearch.knn.index.KNNSettings.lambda$knnMemoryCircuitBreakerSetting$5(KNNSettings.java:360) ~[?:?]
	at org.opensearch.common.settings.Setting.getDefault(Setting.java:422) ~[opensearch-1.3.1.jar:1.3.1]
	at org.opensearch.knn.index.KNNSettings.getSettingValue(KNNSettings.java:289) ~[?:?]
	at org.opensearch.knn.index.KNNSettings.getCircuitBreakerLimit(KNNSettings.java:337) ~[?:?]
	at org.opensearch.knn.index.memory.NativeMemoryCacheManager.initialize(NativeMemoryCacheManager.java:77) ~[?:?]
	at org.opensearch.knn.index.memory.NativeMemoryCacheManager.<init>(NativeMemoryCacheManager.java:55) ~[?:?]
	at org.opensearch.knn.index.memory.NativeMemoryCacheManager.getInstance(NativeMemoryCacheManager.java:65) ~[?:?]
	at org.opensearch.knn.index.KNNCircuitBreaker.initialize(KNNCircuitBreaker.java:60) ~[?:?]
	at org.opensearch.knn.plugin.KNNPlugin.createComponents(KNNPlugin.java:168) ~[?:?]
	at org.opensearch.node.Node.lambda$new$15(Node.java:661) ~[opensearch-1.3.1.jar:1.3.1]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at org.opensearch.node.Node.<init>(Node.java:675) ~[opensearch-1.3.1.jar:1.3.1]
	at org.opensearch.node.Node.<init>(Node.java:319) ~[opensearch-1.3.1.jar:1.3.1]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-1.3.1.jar:1.3.1]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-1.3.1.jar:1.3.1]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:412) ~[opensearch-1.3.1.jar:1.3.1]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178) ~[opensearch-1.3.1.jar:1.3.1]
	... 6 more
uncaught exception in thread [main]
java.lang.IllegalStateException: Physical memory size could not be determined
	at org.opensearch.knn.index.KNNSettings.parseknnMemoryCircuitBreakerValue(KNNSettings.java:374)
	at org.opensearch.knn.index.KNNSettings.lambda$knnMemoryCircuitBreakerSetting$5(KNNSettings.java:360)
	at org.opensearch.common.settings.Setting.getDefault(Setting.java:422)
	at org.opensearch.knn.index.KNNSettings.getSettingValue(KNNSettings.java:289)
	at org.opensearch.knn.index.KNNSettings.getCircuitBreakerLimit(KNNSettings.java:337)
	at org.opensearch.knn.index.memory.NativeMemoryCacheManager.initialize(NativeMemoryCacheManager.java:77)
	at org.opensearch.knn.index.memory.NativeMemoryCacheManager.<init>(NativeMemoryCacheManager.java:55)
	at org.opensearch.knn.index.memory.NativeMemoryCacheManager.getInstance(NativeMemoryCacheManager.java:65)
	at org.opensearch.knn.index.KNNCircuitBreaker.initialize(KNNCircuitBreaker.java:60)
	at org.opensearch.knn.plugin.KNNPlugin.createComponents(KNNPlugin.java:168)
	at org.opensearch.node.Node.lambda$new$15(Node.java:661)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.opensearch.node.Node.<init>(Node.java:675)
	at org.opensearch.node.Node.<init>(Node.java:319)
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242)
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242)
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:412)
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178)
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:169)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.Command.main(Command.java:101)
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:135)
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101)
```

**Comment by ldrolez** [comment]
Hi! Did you find a solution? I got this issue after a Docker upgrade

**Comment by vladaman** [comment]
@ldrolez we moved it to a different VPS instance. The VPS provider we were using was running distro / kernel / virtualization which did not provide information about maximum available memory.

**Comment by ldrolez** [comment]
ok I disabled the KNN plugin to be able to start ES

**Comment by grownuphacker** [comment]
I posted my findings on another issue: 
https://github.com/opensearch-project/k-NN/issues/369#issuecomment-1184697529
