### ISSUE TITLE
Error when creating image with s3 pluging

### ISSUE THREAD

**Issue by mporracindie** [opendistro-for-elasticsearch/community#69]
Im getting this output when running

`docker build -t custom_opendistro .`

```
free(): invalid pointer
SIGABRT: abort
PC=0x7f0f5e840e97 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4afd50, 0xc420057cc0, 0xc420057ce8)
	/usr/lib/go-1.8/src/runtime/cgocall.go:131 +0xe2 fp=0xc420057c90 sp=0xc420057c50
github.com/docker/docker-credential-helpers/secretservice._Cfunc_free(0x2742270)
	github.com/docker/docker-credential-helpers/secretservice/_obj/_cgo_gotypes.go:111 +0x41 fp=0xc420057cc0 sp=0xc420057c90
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List.func5(0x2742270)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:96 +0x60 fp=0xc420057cf8 sp=0xc420057cc0
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List(0x0, 0x756060, 0xc420018360)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:97 +0x217 fp=0xc420057da0 sp=0xc420057cf8
github.com/docker/docker-credential-helpers/secretservice.(*Secretservice).List(0x77e548, 0xc420057e88, 0x410022, 0xc4200182b0)
	<autogenerated>:4 +0x46 fp=0xc420057de0 sp=0xc420057da0
github.com/docker/docker-credential-helpers/credentials.List(0x756ba0, 0x77e548, 0x7560e0, 0xc42000e018, 0x0, 0x10)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:145 +0x3e fp=0xc420057e68 sp=0xc420057de0
github.com/docker/docker-credential-helpers/credentials.HandleCommand(0x756ba0, 0x77e548, 0x7ffc044ae79e, 0x4, 0x7560a0, 0xc42000e010, 0x7560e0, 0xc42000e018, 0x40e398, 0x4d35c0)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:60 +0x16d fp=0xc420057ed8 sp=0xc420057e68
github.com/docker/docker-credential-helpers/credentials.Serve(0x756ba0, 0x77e548)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:41 +0x1cb fp=0xc420057f58 sp=0xc420057ed8
main.main()
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/secretservice/cmd/main_linux.go:9 +0x4f fp=0xc420057f88 sp=0xc420057f58
runtime.main()
	/usr/lib/go-1.8/src/runtime/proc.go:185 +0x20a fp=0xc420057fe0 sp=0xc420057f88
runtime.goexit()
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420057fe8 sp=0xc420057fe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1

rax    0x0
rbx    0x7ffc044ac660
rcx    0x7f0f5e840e97
rdx    0x0
rdi    0x2
rsi    0x7ffc044ac3f0
rbp    0x7ffc044ac760
rsp    0x7ffc044ac3f0
r8     0x0
r9     0x7ffc044ac3f0
r10    0x8
r11    0x246
r12    0x7ffc044ac660
r13    0x1000
r14    0x0
r15    0x30
rip    0x7f0f5e840e97
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
Sending build context to Docker daemon  39.94kB
Step 1/4 : FROM amazon/opendistro-for-elasticsearch:0.9.0
 ---> f2365bb02a57
Step 2/4 : RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-s3/repository-s3-6.7.1.zip
 ---> Using cache
 ---> 242719e27ac1
Step 3/4 : RUN bin/elasticsearch-keystore add --force --stdin s3.client.default.access_key <<< "XXXXXXX"
 ---> Using cache
 ---> 76a530fd1503
Step 4/4 : RUN bin/elasticsearch-keystore add --force --stdin s3.client.default.secret_key <<< "XXXXXXX"
 ---> Using cache
 ---> f99c87cd0df2
Successfully built f99c87cd0df2
Successfully tagged custom_opendistro:latest
```

Running the server works fine and i wasnt able to find any trouble but i thought it might be important to point this error up.

**Comment by aetter** [comment]
Hi @mporracindie, are you on Ubuntu 18.04 by any chance? Looks like it might be a known Docker issue with a workaround: https://github.com/docker/docker-credential-helpers/issues/103

**Comment by mporracindie** [comment]
@aetter That was it. Thanks!
