### ISSUE TITLE
AWS Cloud Plugin 

### ISSUE THREAD

**Issue by hermes-pimentel** [opendistro-for-elasticsearch/community#93]
Hi there! =D

I want to deploy a ES Cluster with spot instances on AWS using this plugin https://github.com/elastic/elasticsearch-cloud-aws for instance discovery. There any way to accomplish this using Opendistro for Elasticsearch?

Other question, there are any documentation avaliable showing how to run Opendistro in cluster mode besides with docker? Or a complete description of the configuration parameters avaliable?

**Comment by alolita** [comment]
@hermes-pimentel is this still a requirement for you? If so, let us know. Apologies for a delayed response.

**Comment by chynkm** [comment]
+1 

I get the following error on installation:

`@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.net.SocketPermission * connect,resolve
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
-> Failed installing discovery-ec2
-> Rolling back discovery-ec2
Exception in thread "main" -> Rolled back discovery-ec2
java.lang.IllegalStateException: unable to read from standard input; is standard input open and a tty attached?
	at org.elasticsearch.cli.Terminal$SystemTerminal.readText(Terminal.java:273)
	at org.elasticsearch.plugins.PluginSecurity.prompt(PluginSecurity.java:74)
	at org.elasticsearch.plugins.PluginSecurity.confirmPolicyExceptions(PluginSecurity.java:67)
	at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:875)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:254)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:224)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:91)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)`

**Comment by chynkm** [comment]
Found a solution. Use `bin/elasticsearch-plugin install --batch discovery-ec2`
